
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS'
export const CLEAR_RESEARCHER_PROJECTS = 'CLEAR_RESEARCHER_PROJECTS'
export const CLEAR_ADMIN_PROJECTS = 'CLEAR_ADMIN_PROJECTS'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_STREAMS = 'FETCH_STREAMS'
export const FETCH_STREAM = 'FETCH_STREAM'
export const CREATE_STREAM = 'CREATE_STREAM'
export const EDIT_STREAM = 'EDIT_STREAM'
export const DELETE_STREAM = 'DELETE_STREAM'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECT = 'FETCH_PROJECT'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_TEMP = 'CREATE_PROJECT_TEMP'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const FETCH_RESEARCHER_PROJECTS = 'FETCH_RESEARCHER_PROJECTS'

export const FETCH_ADMIN_PROJECTS = 'FETCH_ADMIN_PROJECTS'

export const FETCH_PROJECT_DETAIL = 'FETCH_PROJECT_DETAIL'

export const FETCH_LEVEL_DEVELOPMENTS = 'FETCH_LEVEL_DEVELOPMENTS'
export const FETCH_LEVEL_DEVELOPMENT = 'FETCH_LEVEL_DEVELOPMENT'
export const CREATE_LEVEL_DEVELOPMENT = 'CREATE_LEVEL_DEVELOPMENT'
export const EDIT_LEVEL_DEVELOPMENT = 'EDIT_LEVEL_DEVELOPMENT'
export const DELETE_LEVEL_DEVELOPMENT = 'DELETE_LEVEL_DEVELOPMENT'

export const FETCH_TRANSMISSION_METHODS = 'FETCH_TRANSMISSION_METHODS'
export const FETCH_TRANSMISSION_METHOD = 'FETCH_TRANSMISSION_METHOD'
export const CREATE_TRANSMISSION_METHOD = 'CREATE_TRANSMISSION_METHOD'
export const EDIT_TRANSMISSION_METHOD = 'EDIT_TRANSMISSION_METHOD'
export const DELETE_TRANSMISSION_METHOD = 'DELETE_TRANSMISSION_METHOD'

export const FETCH_FIELDS = 'FETCH_FIELDS'
export const FETCH_FIELD = 'FETCH_FIELD'
export const CREATE_FIELD = 'CREATE_FIELD'
export const EDIT_FIELD = 'EDIT_FIELD'
export const DELETE_FIELD = 'DELETE_FIELD'

export const FETCH_STATUSES = 'FETCH_STATUSES'
export const FETCH_STATUS = 'FETCH_STATUS'
export const CREATE_STATUS = 'CREATE_STATUS'
export const EDIT_STATUS = 'EDIT_STATUS'
export const DELETE_STATUS = 'DELETE_STATUS'

export const LOADING = 'LOADING'
export const LOADED = 'LOADED'

export const FETCH_FUNCTIONS = 'FETCH_FUNCTIONS'
export const CREATE_FUNCTION = 'CREATE_FUNCTION'
export const EDIT_FUNCTION = 'EDIT_FUNCTION'
export const DELETE_FUNCTION = 'DELETE_FUNCTION'

export const FETCH_FUNCTIONS_ADMIN = 'FETCH_FUNCTIONS_ADMIN'
export const CREATE_FUNCTION_ADMIN = 'CREATE_FUNCTION_ADMIN'
export const EDIT_FUNCTION_ADMIN = 'EDIT_FUNCTION_ADMIN'
export const DELETE_FUNCTION_ADMIN = 'DELETE_FUNCTION_ADMIN'

export const FETCH_DOMAINS = 'FETCH_DOMAINS'
export const FETCH_DOMAIN = 'FETCH_DOMAIN'
export const CREATE_DOMAIN = 'CREATE_DOMAIN'
export const EDIT_DOMAIN = 'EDIT_DOMAIN'
export const DELETE_DOMAIN = 'DELETE_DOMAIN'

export const FETCH_DOMAINS_ADMIN = 'FETCH_DOMAINS_ADMIN'
export const FETCH_DOMAIN_ADMIN = 'FETCH_DOMAIN_ADMIN'
export const CREATE_DOMAIN_ADMIN = 'CREATE_DOMAIN_ADMIN'
export const EDIT_DOMAIN_ADMIN = 'EDIT_DOMAIN_ADMIN'
export const DELETE_DOMAIN_ADMIN = 'DELETE_DOMAIN_ADMIN'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'

export const FETCH_ROLES = 'FETCH_ROLES'
export const FETCH_ROLE = 'FETCH_ROLE'
export const CREATE_ROLE = 'CREATE_ROLE'
export const EDIT_ROLE = 'EDIT_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'

export const FETCH_ROLES_ADMIN = 'FETCH_ROLES_ADMIN'
export const FETCH_ROLE_ADMIN = 'FETCH_ROLE_ADMIN'
export const CREATE_ROLE_ADMIN = 'CREATE_ROLE_ADMIN'
export const EDIT_ROLE_ADMIN = 'EDIT_ROLE_ADMIN'
export const DELETE_ROLE_ADMIN = 'DELETE_ROLE_ADMIN'

export const FETCH_ROLES_OF_GROUP = 'FETCH_ROLES_OF_GROUP'
export const FETCH_ROLE_OF_GROUP = 'FETCH_ROLE_OF_GROUP'
export const CREATE_ROLES_OF_GROUP = 'CREATE_ROLES_OF_GROUP'
export const EDIT_ROLES_OF_GROUP = 'EDIT_ROLES_OF_GROUP'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USER = 'FETCH_USER'
export const CREATE_USER = 'CREATE_USER'
export const EDIT_USER = 'EDIT_USER'
export const DELETE_USER = 'DELETE_USER'

export const FETCH_RESEARCH_GROUPS = 'FETCH_GROUPS'
export const FETCH_RESEARCH_GROUP = 'FETCH_GROUP'
export const CREATE_RESEARCH_GROUP = 'CREATE_GROUP'
export const EDIT_RESEARCH_GROUP = 'EDIT_GROUP'
export const DELETE_RESEARCH_GROUP = 'DELETE_GROUP'

export const FETCH_RESEARCH_GROUPS_ADMIN = 'FETCH_GROUPS_ADMIN'
export const FETCH_RESEARCH_GROUP_ADMIN = 'FETCH_GROUP_ADMIN'
export const CREATE_RESEARCH_GROUP_ADMIN = 'CREATE_GROUP_ADMIN'
export const EDIT_RESEARCH_GROUP_ADMIN = 'EDIT_GROUP_ADMIN'
export const DELETE_RESEARCH_GROUP_ADMIN = 'DELETE_GROUP_ADMIN'

export const FETCH_FAQS = 'FETCH_FAQS'
export const FETCH_FAQ = 'FETCH_FAQ'
export const CREATE_FAQ = 'CREATE_FAQ'
export const EDIT_FAQ = 'EDIT_FAQ'
export const DELETE_FAQ = 'DELETE_FAQ'

export const FETCH_FAQS_ADMIN = 'FETCH_FAQS_ADMIN'
export const FETCH_FAQ_ADMIN = 'FETCH_FAQ_ADMIN'
export const CREATE_FAQ_ADMIN = 'CREATE_FAQ_ADMIN'
export const EDIT_FAQ_ADMIN = 'EDIT_FAQ_ADMIN'
export const DELETE_FAQ_ADMIN = 'DELETE_FAQ_ADMIN'

export const FETCH_CONTACTS = 'FETCH_CONTACTS'
export const FETCH_CONTACT = 'FETCH_CONTACT'
export const CREATE_CONTACT = 'CREATE_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export const FETCH_CONTACTS_ADMIN = 'FETCH_CONTACTS_ADMIN'
export const FETCH_CONTACT_ADMIN = 'FETCH_CONTACT_ADMIN'
export const CREATE_CONTACT_ADMIN = 'CREATE_CONTACT_ADMIN'
export const EDIT_CONTACT_ADMIN = 'EDIT_CONTACT_ADMIN'
export const DELETE_CONTACT_ADMIN = 'DELETE_CONTACT_ADMIN'

export const FETCH_CUSTOMER_CONTACTS = 'FETCH_CUSTOMER_CONTACTS'
export const FETCH_CUSTOMER_CONTACT = 'FETCH_CUSTOMER_CONTACT'
export const CREATE_CUSTOMER_CONTACT = 'CREATE_CUSTOMER_CONTACT'
export const EDIT_CUSTOMER_CONTACT = 'EDIT_CUSTOMER_CONTACT'
export const DELETE_CUSTOMER_CONTACT = 'DELETE_CUSTOMER_CONTACT'

export const FETCH_CUSTOMER_CONTACTS_ADMIN = 'FETCH_CUSTOMER_CONTACTS_ADMIN'
export const FETCH_CUSTOMER_CONTACT_ADMIN = 'FETCH_CUSTOMER_CONTACT_ADMIN'
export const CREATE_CUSTOMER_CONTACT_ADMIN = 'CREATE_CUSTOMER_CONTACT_ADMIN'
export const EDIT_CUSTOMER_CONTACT_ADMIN = 'EDIT_CUSTOMER_CONTACT_ADMIN'
export const DELETE_CUSTOMER_CONTACT_ADMIN = 'DELETE_CUSTOMER_CONTACT_ADMIN'

export const FETCH_ABOUTS = 'FETCH_ABOUTS'
export const FETCH_ABOUT = 'FETCH_ABOUT'
export const CREATE_ABOUT = 'CREATE_ABOUT'
export const EDIT_ABOUT = 'EDIT_ABOUT'
export const DELETE_ABOUT = 'DELETE_ABOUT'

export const FETCH_ABOUTS_ADMIN = 'FETCH_ABOUTS_ADMIN'
export const FETCH_ABOUT_ADMIN = 'FETCH_ABOUT_ADMIN'
export const CREATE_ABOUT_ADMIN = 'CREATE_ABOUT_ADMIN'
export const EDIT_ABOUT_ADMIN = 'EDIT_ABOUT_ADMIN'
export const DELETE_ABOUT_ADMIN = 'DELETE_ABOUT_ADMIN'

export const EDIT_USER_FUNCTION = 'EDIT_USER_FUNCTION'

export const BLOCK_NAVIGATION = 'BLOCK_NAVIGATION'
export const UNBLOCK_NAVIGATION = 'UNBLOCK_NAVIGATION'