export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_STREAMS = 'FETCH_STREAMS'
export const FETCH_STREAM = 'FETCH_STREAM'
export const CREATE_STREAM = 'CREATE_STREAM'
export const EDIT_STREAM = 'EDIT_STREAM'
export const DELETE_STREAM = 'DELETE_STREAM'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_PROJECT = 'FETCH_PROJECT'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_TEMP = 'CREATE_PROJECT_TEMP'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const FETCH_PROJECT_DETAIL = 'FETCH_PROJECT_DETAIL'

export const FETCH_LEVEL_DEVELOPMENTS = 'FETCH_LEVEL_DEVELOPMENTS'
export const FETCH_LEVEL_DEVELOPMENT = 'FETCH_LEVEL_DEVELOPMENT'
export const CREATE_LEVEL_DEVELOPMENT = 'CREATE_LEVEL_DEVELOPMENT'
export const EDIT_LEVEL_DEVELOPMENT = 'EDIT_LEVEL_DEVELOPMENT'

export const FETCH_TRANSMISSION_METHODS = 'FETCH_TRANSMISSION_METHODS'
export const FETCH_TRANSMISSION_METHOD = 'FETCH_TRANSMISSION_METHOD'
export const CREATE_TRANSMISSION_METHOD = 'CREATE_TRANSMISSION_METHOD'
export const EDIT_TRANSMISSION_METHOD = 'EDIT_TRANSMISSION_METHOD'

export const FETCH_FIELDS = 'FETCH_FIELDS'
export const FETCH_FIELD = 'FETCH_FIELD'
export const CREATE_FIELD = 'CREATE_FIELD'
export const EDIT_FIELD = 'EDIT_FIELD'

export const FETCH_STATUSES = 'FETCH_STATUSES'
export const FETCH_STATUS = 'FETCH_STATUS'
export const CREATE_STATUS = 'CREATE_STATUS'
export const EDIT_STATUS = 'EDIT_STATUS'

export const LOADING = 'LOADING'
export const LOADED = 'LOADED'

export const FETCH_FUNCTIONS = 'FETCH_FUNCTIONS'

export const FETCH_DOMAINS = 'FETCH_DOMAINS'
export const CREATE_DOMAIN = 'CREATE_DOMAIN'
export const EDIT_DOMAIN = 'EDIT_DOMAIN'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'

export const FETCH_ROLES = 'FETCH_ROLES'
export const FETCH_ROLE = 'FETCH_ROLE'
export const CREATE_ROLE = 'CREATE_ROLE'
export const EDIT_ROLE = 'EDIT_ROLE'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USER = 'FETCH_USER'
export const CREATE_USER = 'CREATE_USER'
export const EDIT_USER = 'EDIT_USER'

export const BLOCK_NAVIGATION = 'BLOCK_NAVIGATION'
export const UNBLOCK_NAVIGATION = 'UNBLOCK_NAVIGATION'