module.exports = {
   ROLE_SUPER_ADMIN : 'SAD',
   ROLE_ADMIN : 'ADMIN',
   ROLE_NNC : 'NNC',
   ROLE_OTHER : 'OTHER',

   LOGIN_URL : '/users/login',
   SIGNUP_URL : '/users',
   FIELD_URL: '/fields',
   FIELD_ADMIN_URL: '/admin/fields',
   LEVEL_URL : '/developmentLevels',
   LEVEL_ADMIN_URL : '/admin/developmentLevels',
   CATEGORY_URL : '/categories',
   CATEGORY_ADMIN_URL : '/admin/categories',
   PROJECTS_URL : '/projects/status',
   PROJECTS_COMMERCIAL_URL : '/projects/commercial',
   PROJECTS_RESEARCHING_URL : '/projects/researching',
   TRANSMISSION_URL : '/transmissionMethods',
   TRANSMISSION_ADMIN_URL : '/admin/transmissionMethods',
   STATUS_URL : '/statuses',
   STATUS_ADMIN_URL : '/admin/statuses',
   FUNCTIONS_URL : '/admin/functions',
   DOMAINS_URL : '/admin/domains',
   ROLES_URL : '/roles',
   ROLES_ADMIN_URL : '/admin/roles',
} 