module.exports = {
   ROLE_SUPER_ADMIN : 'SAD',
   ROLE_ADMIN : 'AD',
   ROLE_NNC : 'NNC',
   ROLE_USER : 'USR',

   LOGIN_URL : '/users/login',
   SIGNUP_URL : '/users',
   FIELD_URL: '/fields',
   FIELD_ADMIN_URL: '/admin/fields',
   LEVEL_URL : '/developmentLevels',
   LEVEL_ADMIN_URL : '/admin/developmentLevels',
   CATEGORY_URL : '/categories',
   CATEGORY_ADMIN_URL : '/admin/categories',
   PROJECTS_URL : '/projects/status',
   PROJECTS_BY_DOMAIN_ID_URL : '/admin/projects/domain',
   PROJECTS_COMMERCIAL_URL : '/projects/commercial',
   PROJECTS_ADMIN_COMMERCIAL_URL : '/admin/projects/commercial',
   PROJECTS_RESEARCHING_URL : '/projects/researching',
   PROJECTS_ADMIN_RESEARCHING_URL : '/admin/projects/researching',
   TRANSMISSION_URL : '/transmissionMethods',
   TRANSMISSION_ADMIN_URL : '/admin/transmissionMethods',
   STATUS_URL : '/statuses',
   STATUS_ADMIN_URL : '/admin/statuses',
   FUNCTIONS_URL : '/admin/functions',
   DOMAINS_URL : '/admin/domains',
   ROLES_URL : '/roles',
   ROLES_ADMIN_URL : '/admin/roles',
   ROLE_OF_GROUP_ADMIN_URL : '/admin/role-of-groups',
   USER_ADMIN_URL : '/admin/users',
   USER_FUNCTION_ADMIN_URL : '/admin/userFunctions',
   RESEARCH_GROUP_ADMIN_URL : '/admin/research-groups',
   RESEARCH_GROUP_DETAIL_ADMIN_URL : '/admin/group-details',
   FAQ_URL : '/faqs',
   FAQ_ADMIN_URL : '/admin/faqs',
   CONTACT_URL : '/contacts',
   CONTACT_ADMIN_URL : '/admin/contacts',
   CUSTOMER_CONTACT_URL : '/customer-contacts',
   CUSTOMER_CONTACT_ADMIN_URL : '/admin/customer-contacts',
   ABOUT_ADMIN_URL : '/admin/about-pages',
} 